name: Testar build React reutilizável

on:
  push:
    branches:
      - develop

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: esterekarklis/github-workflows/.github/workflows/react-build.yml@main
    with:
      node_version: "18.19.1"
      working_directory: "react"
      output_directory: "public-react"
      commit_build: true
      commit_message: "chore: atualiza build React"